"""plots: Auto Plot Code bookkeeping (round B).

A plot's code is now generated by the server —
{supplierCode}-{YYMM}-{running}, e.g. "JPS-2605-001" — instead of typed by
whoever creates the plot. This migration adds only the bookkeeping the
generator needs; the plot_code column itself is unchanged.

  1. plot_code_source       VARCHAR(20)  NULL   'auto' | 'manual' | 'legacy'
  2. plot_code_series_key   VARCHAR(255) NULL   server-derived series identity
  3. plot_code_running_no   INTEGER      NULL   position within that series

Mirrors the Auto Lot columns on plot_cycles (migrations 0042/0048/0049) on
purpose: same three-part shape (source / series key / running number), same
partial-unique concurrency backstop, so the two generated identifiers this
system mints behave identically and can be reasoned about once.

Why NULL is the right default for every existing row: NULL means "this code
predates the generator". The 43 plots on UAT carry hand-entered codes (several
of them a person's name typed into the wrong field) and are deliberately NOT
backfilled, renamed or renumbered — a plot code is printed on field signage and
is the folder name under which that plot's inspection photos already live in
object storage, so rewriting one would orphan real data for no benefit. They
keep reading and editing exactly as before; only NEW plots are generated.
`legacy` is reserved as an explicit label for them if a later round ever wants
to stamp it — no code path writes it now, and no backfill runs here.

Constraints/indexes added:

  ck_plots_plot_code_source_allowed
      plot_code_source IS NULL OR IN ('auto','manual','legacy')

  ck_plots_auto_plot_code_requires_fields
      an 'auto' row must carry BOTH its series key and its running number —
      without them the code it was rendered from cannot be re-derived, and the
      running sequence for that series could not be continued correctly.

  ck_plots_plot_code_running_no_positive
      running numbers start at 1 (mirrors ck_plot_cycles_lot_running_no_positive).

  uq_plots_auto_code_series_running
      UNIQUE(plot_code_series_key, plot_code_running_no) over 'auto' rows only.
      THE concurrency backstop: two imports creating plots for the same
      supplier in the same month can both read "max running = 7" before either
      inserts. The row lock on the supplier is not enough (a supplier row is
      not locked by a plot insert), so the DB refuses the duplicate and the
      loser surfaces as a clean 409 rather than two plots sharing a code.
      Scoped to 'auto' so legacy/manual rows (all NULL here) never participate.

The pre-existing uq_plots_supplier_code (migration 0014) still guarantees the
rendered code is unique per supplier; this index guarantees the SEQUENCE behind
it is allocated exactly once.

Additive and data-free: no UPDATE/INSERT/DELETE, no change to any other table,
no RLS policy/grant/role/ownership change. Transactional DDL — any failure
rolls the whole migration back. Downgrade drops exactly what upgrade added.

Revision ID: 0053_plots_auto_plot_code
Revises: 0052_suppliers_menu_update
Create Date: 2026-09-04 00:00:00

(Revision id kept <= 32 chars for alembic_version.version_num.)
"""
from __future__ import annotations

from alembic import op

revision = "0053_plots_auto_plot_code"
down_revision = "0052_suppliers_menu_update"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        ALTER TABLE plots ADD COLUMN plot_code_source VARCHAR(20);
        ALTER TABLE plots ADD COLUMN plot_code_series_key VARCHAR(255);
        ALTER TABLE plots ADD COLUMN plot_code_running_no INTEGER;

        ALTER TABLE plots ADD CONSTRAINT ck_plots_plot_code_source_allowed
            CHECK (
                plot_code_source IS NULL
                OR plot_code_source IN ('auto', 'manual', 'legacy')
            );

        ALTER TABLE plots ADD CONSTRAINT ck_plots_auto_plot_code_requires_fields
            CHECK (
                plot_code_source IS DISTINCT FROM 'auto'
                OR (
                    plot_code_series_key IS NOT NULL
                    AND plot_code_running_no IS NOT NULL
                )
            );

        ALTER TABLE plots ADD CONSTRAINT ck_plots_plot_code_running_no_positive
            CHECK (plot_code_running_no IS NULL OR plot_code_running_no >= 1);

        CREATE UNIQUE INDEX uq_plots_auto_code_series_running
            ON plots (plot_code_series_key, plot_code_running_no)
            WHERE plot_code_source = 'auto';
        """
    )


def downgrade() -> None:
    op.execute(
        """
        DROP INDEX IF EXISTS uq_plots_auto_code_series_running;
        ALTER TABLE plots DROP CONSTRAINT IF EXISTS ck_plots_plot_code_running_no_positive;
        ALTER TABLE plots DROP CONSTRAINT IF EXISTS ck_plots_auto_plot_code_requires_fields;
        ALTER TABLE plots DROP CONSTRAINT IF EXISTS ck_plots_plot_code_source_allowed;
        ALTER TABLE plots DROP COLUMN IF EXISTS plot_code_running_no;
        ALTER TABLE plots DROP COLUMN IF EXISTS plot_code_series_key;
        ALTER TABLE plots DROP COLUMN IF EXISTS plot_code_source;
        """
    )
