#!/usr/bin/env python3
"""
Chia Tai Web App Standard — Project Setup

รัน script นี้ครั้งเดียวเพื่อ:
1. ตรวจ environment (Docker, Node.js, Python, ports)
2. ถามแค่ 2 อย่าง (ชื่อ project + ประเภท user)
3. Generate files + scaffold project structure
4. Start app (docker compose + migrations)

Usage:
    python scripts/setup.py
    python scripts/setup.py --database-mode existing
"""
from __future__ import annotations

import argparse
import os
import re
import secrets
import socket
import subprocess
import sys
import tempfile
import time
from dataclasses import dataclass, field
from pathlib import Path

# scaffold functions ใช้ร่วมกับ init_project.py — ดู scripts/scaffold.py
sys.path.insert(0, str(Path(__file__).resolve().parent))
from scaffold import (
    _scaffold_backend,
    _scaffold_docker,
    _scaffold_frontend,
    _scaffold_global_standards,
    _scaffold_tooling,
)
from _stdio import (
    ensure_utf8_stdio as _ensure_utf8_stdio_impl,
    getpass_masked as _getpass_masked,
)
from password_policy import password_strength_error

# Identifier whitelist for SQL identifiers (database / role names).
# psql -v variables can be quoted server-side via `:'name'` (literals) and
# `:"name"` (identifiers) — but we still validate db_name/db_user at the
# host before composing the SQL to fail fast with a clear error rather
# than letting psql reject a 200-char password as an identifier later.
_IDENT_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def _gen_dev_db_password() -> str:
    """Generate a random URL-safe password for local-dev DB.

    Replaces the old hardcoded 'devpassword123' default — even dev
    credentials shouldn't be identical across every scaffolded project.
    URL-safe (`-` / `_`) keeps it copy-paste-able into psql / DSN URIs
    without escaping. 16 bytes ≈ 22 chars, sufficient for local dev.
    """
    return secrets.token_urlsafe(16)


# Current security baseline — kept in sync with scripts/migrate-security.py
# CURRENT_BASELINE. Anything generated by this setup.py is by definition
# the latest baseline; we stamp it so `migrate-security.py --check` can
# distinguish a fresh scaffold from an unmigrated older project.
_SECURITY_BASELINE_VERSION = "v3.0.2"
_SECURITY_BASELINE_FILE = ".security-baseline"


def _write_security_baseline(root: Path, source: str) -> None:
    """Drop a .security-baseline marker at project root.

    `source` is 'scaffold' here (migrate-security.py writes 'migration').
    The marker is tracked-friendly plain KEY=VALUE so anyone can grep it.
    """
    from datetime import date as _date
    content = (
        "# Security baseline marker — see docs/migration-security-v3.0.2.md\n"
        f"SECURITY_BASELINE={_SECURITY_BASELINE_VERSION}\n"
        f"APPLIED={_date.today().isoformat()}\n"
        f"SOURCE={source}\n"
    )
    (root / _SECURITY_BASELINE_FILE).write_text(content, encoding="utf-8")


# ───────────────────────────────────────────────────────────────
# Constants
# ───────────────────────────────────────────────────────────────

REQUIRED_PORTS = {
    5432: "PostgreSQL",
    8000: "Backend API",
    5173: "Frontend",
}

MODEL_DEFAULT = "claude-sonnet-4-20250514"


# ───────────────────────────────────────────────────────────────
# Helpers
# ───────────────────────────────────────────────────────────────


# Re-exported for callers (tests + this module) that historically imported
# _ensure_utf8_stdio from setup. The implementation lives in scripts/_stdio.py
# so init_project.py can share it (F5).
def _ensure_utf8_stdio() -> None:
    """Make stdout/stderr utf-8 so emoji + Thai text don't crash on Windows cp1252."""
    _ensure_utf8_stdio_impl()


def _resolve_argv(cmd: str | list[str]) -> str | list[str]:
    """Resolve a list command's executable to its full path.

    On Windows, tools like `npm`/`npx` ship as `npm.CMD` and CreateProcess
    (shell=False) does NOT search PATHEXT — so a bare ``["npm", ...]`` raises
    FileNotFoundError even though npm is on PATH (this is exactly what crashed
    the wizard at the frontend-install step on every Windows machine).
    ``shutil.which()`` DOES honour PATHEXT and returns the full ``npm.CMD``
    path, which subprocess can launch with shell=False — keeping the no-shell
    policy (audit #4). Str commands (shell=True) are returned unchanged; a
    name we can't resolve is left as-is so the caller still sees the failure.
    """
    import shutil
    if isinstance(cmd, list) and cmd:
        exe = shutil.which(cmd[0])
        if exe:
            return [exe, *cmd[1:]]
    return cmd


def _run(
    cmd: str | list[str],
    cwd: Path | None = None,
    capture: bool = True,
    env: dict[str, str] | None = None,
) -> tuple[int, str]:
    """Run a command and capture stdout+stderr.

    Prefer list-form argv when possible — it skips the shell entirely
    (no quoting / no command-injection surface). Pass a str only when
    you need shell features (pipes, redirects, builtins like `start`);
    we honour shell=True only in that case. See audit finding #4.

    encoding='utf-8' + errors='replace' avoids the Windows cp1252 decode
    crash when psql/docker emit utf-8 bytes (postgres locale messages,
    container labels, Thai user input echoed back) — see F4.
    """
    cmd = _resolve_argv(cmd)
    use_shell = isinstance(cmd, str)
    try:
        result = subprocess.run(
            cmd, shell=use_shell, cwd=cwd,
            capture_output=capture, text=True,
            encoding="utf-8", errors="replace",
            env=env,
        )
    except FileNotFoundError as exc:
        # Executable not on PATH — return a non-zero code instead of raising
        # so callers degrade gracefully rather than crashing the whole setup.
        return 127, str(exc)
    return result.returncode, (result.stdout + result.stderr).strip()


def _run_visible(cmd: str | list[str], cwd: Path | None = None) -> int:
    """Run command with visible output. Same str-vs-list policy as _run."""
    cmd = _resolve_argv(cmd)
    try:
        result = subprocess.run(cmd, shell=isinstance(cmd, str), cwd=cwd)
    except FileNotFoundError:
        # Missing executable → non-zero code, never raise (audit/dogfood
        # 2026-06-01: a bare ["npm", ...] used to raise here and abort setup).
        return 127
    return result.returncode


def _port_in_use(port: int) -> bool:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        return s.connect_ex(("127.0.0.1", port)) == 0


def _suggest_free_db_port(env: "EnvCheck | None" = None,
                          start: int = 5433, end: int = 5439) -> int:
    """Find the first free port for a new postgres dev container.

    Walks `start..end` (inclusive), skipping anything we already know is
    in use. Falls back to 5435 if nothing in range is free — the user
    can still override at the prompt.
    """
    known_busy = set(env.port_conflicts) if env else set()
    for port in range(start, end + 1):
        if port in known_busy:
            continue
        if _port_in_use(port):
            continue
        return port
    return 5435


def _ask_new_container_port(env: "EnvCheck | None" = None) -> int:
    """Resolve the host port for a freshly-created DB container.

    If 5432 is free we just take it (the convention, matches every doc).
    If 5432 is busy we surface the conflict, scan 5433-5439 for a free
    port, and prompt the user — defaulting to that suggestion so a plain
    Enter is the right answer. The wizard never silently picks a non-
    default port that would later mismatch the .env / compose mapping.
    """
    if not _port_in_use(5432) and not (env and 5432 in env.port_conflicts):
        return 5432
    suggested = _suggest_free_db_port(env)
    print()
    print(f"   ⚠️  Port 5432 ถูกใช้งานอยู่ — DB container ใหม่ต้องใช้ port อื่น")
    print(f"      port ว่างถัดไปที่เจอ: {suggested}")
    while True:
        raw = input(f"   Port สำหรับ DB container ใหม่ [default: {suggested}]: ").strip()
        if not raw:
            return suggested
        try:
            chosen = int(raw)
        except ValueError:
            print("   ⚠️  ใส่ตัวเลขเท่านั้น")
            continue
        if not (1024 <= chosen <= 65535):
            print("   ⚠️  port ต้องอยู่ระหว่าง 1024-65535")
            continue
        if _port_in_use(chosen):
            print(f"   ⚠️  port {chosen} ก็ถูกใช้งานอยู่ — ลองอันอื่น")
            continue
        return chosen


def _slug_from_folder(folder_name: str) -> str:
    """Convert folder name to kebab-case slug."""
    slug = folder_name.lower()
    slug = re.sub(r"[^a-z0-9]+", "-", slug)
    slug = slug.strip("-")
    return slug[:50]


def _prompt(question: str, default: str = "", required: bool = True) -> str:
    while True:
        hint = f" [{default}]" if default else ""
        answer = input(f"{question}{hint}: ").strip()
        if not answer and default:
            return default
        if not answer and required:
            print("    ⚠️  กรุณาระบุค่า")
            continue
        return answer


def _confirm(question: str, default_yes: bool = True) -> bool:
    hint = "Y/n" if default_yes else "y/N"
    answer = input(f"{question} [{hint}]: ").strip().lower()
    if not answer:
        return default_yes
    return answer in ("y", "yes")


# ───────────────────────────────────────────────────────────────
# Step 1: Check environment
# ───────────────────────────────────────────────────────────────


@dataclass
class EnvCheck:
    docker_cli_ok: bool = False  # docker binary present
    docker_engine_ok: bool = False  # docker daemon responding
    docker_ok: bool = False  # legacy combined flag (cli AND engine)
    docker_version: str = ""
    node_ok: bool = False
    node_version: str = ""
    python_ok: bool = False
    python_version: str = ""
    ports_ok: dict[int, bool] = field(default_factory=dict)
    port_conflicts: list[int] = field(default_factory=list)

    @property
    def native_pg_on_5432(self) -> bool:
        """True if port 5432 is in use (almost certainly native PostgreSQL).

        We don't try to probe the actual protocol — anyone listening on
        5432 is treated as a postgres-compatible server. This matches the
        existing port-check message ('PostgreSQL').
        """
        return 5432 in self.port_conflicts

    @property
    def can_proceed(self) -> bool:
        return self.docker_ok and self.node_ok and not self.port_conflicts


def check_environment() -> EnvCheck:
    print()
    print("🔍 ตรวจสอบ environment...")
    print()
    env = EnvCheck()

    # Docker
    code, out = _run(["docker", "--version"])
    env.docker_cli_ok = code == 0
    if env.docker_cli_ok:
        env.docker_version = out.split("version")[-1].strip().split(",")[0].strip()
        print(f"   Docker          ✅  {env.docker_version}")
    else:
        print("   Docker          ❌  ไม่พบ — ติดตั้ง Docker Desktop ก่อน")
        print("                       https://www.docker.com/products/docker-desktop/")

    # Docker running
    if env.docker_cli_ok:
        code, _ = _run(["docker", "info"])
        if code != 0:
            env.docker_engine_ok = False
            print("   Docker Engine   ❌  Docker ไม่ได้รัน — เปิด Docker Desktop ก่อน")
        else:
            env.docker_engine_ok = True
            print("   Docker Engine   ✅  running")

    # Combined flag — kept for backward compat with anything still reading it
    env.docker_ok = env.docker_cli_ok and env.docker_engine_ok

    # Node.js
    code, out = _run(["node", "--version"])
    env.node_ok = code == 0
    if env.node_ok:
        env.node_version = out.strip()
        # ตรวจ version >= 18
        try:
            major = int(env.node_version.lstrip("v").split(".")[0])
            if major < 18:
                env.node_ok = False
                print(f"   Node.js         ⚠️  {env.node_version} — ต้องการ v18+ "
                      f"(https://nodejs.org/)")
            else:
                print(f"   Node.js         ✅  {env.node_version}")
        except ValueError:
            print(f"   Node.js         ✅  {env.node_version}")
    else:
        print("   Node.js         ❌  ไม่พบ — ติดตั้งจาก https://nodejs.org/")

    # Python — require >= 3.12 (scaffold pins py3.12)
    code, out = _run(["python", "--version"])
    if code != 0:
        code, out = _run(["python3", "--version"])
    env.python_ok = code == 0
    if env.python_ok:
        env.python_version = out.strip()
        try:
            parts = env.python_version.replace("Python", "").strip().split(".")
            major, minor = int(parts[0]), int(parts[1])
            if (major, minor) < (3, 12):
                env.python_ok = False
                print(f"   Python          ❌  {env.python_version} — ต้องการ 3.12+ "
                      f"(scaffold pin python:3.12)")
            else:
                print(f"   Python          ✅  {env.python_version}")
        except (ValueError, IndexError):
            print(f"   Python          ✅  {env.python_version} (version parse skipped)")

    # Ports
    print()
    for port, name in REQUIRED_PORTS.items():
        in_use = _port_in_use(port)
        env.ports_ok[port] = not in_use
        if in_use:
            env.port_conflicts.append(port)
            print(f"   Port {port}       ⚠️  ถูกใช้งานอยู่ ({name})")
        else:
            print(f"   Port {port}       ✅  ว่าง ({name})")

    print()
    return env


def handle_env_issues(env: EnvCheck, *, database_mode: str = "new") -> bool:
    """Return True if can proceed.

    Docker policy:
    - Engine running → proceed (current behavior).
    - Engine NOT running BUT native PostgreSQL on 5432 → warn + proceed.
      The DB choose-flow will route to the "use native pg" branch.
    - Engine NOT running AND no native pg → hard fail (current behavior).

    Existing-database mode does not use Docker or create database objects,
    so Docker is optional in that mode.
    """
    if database_mode == "existing":
        if not env.docker_cli_ok or not env.docker_engine_ok:
            print("ℹ️  Existing database mode — ข้าม Docker requirement")
            print()
    elif not env.docker_cli_ok:
        print("❌ ต้องมี Docker Desktop ก่อน — ติดตั้งแล้วรัน script ใหม่")
        return False

    if database_mode != "existing" and not env.docker_engine_ok:
        if env.native_pg_on_5432:
            print("⚠️  Docker Engine ไม่ได้รัน แต่พบ PostgreSQL บน port 5432")
            print("   จะใช้ native PostgreSQL แทน Docker container")
            print("   (ถ้าต้องการใช้ Docker — เปิด Docker Desktop แล้วรัน script ใหม่)")
            print()
        else:
            print("❌ ต้องมี Docker Engine ก่อน — เปิด Docker Desktop แล้วรัน script ใหม่")
            return False

    if not env.node_ok:
        print("❌ ต้องมี Node.js v18+ ก่อน — ติดตั้งแล้วรัน script ใหม่")
        return False

    if env.port_conflicts:
        # Port 5432 is special: a busy 5432 almost always means an existing
        # PostgreSQL the user can reuse. Step 1b (choose-DB) detects that
        # server's real port and either reuses it or auto-picks a free port
        # (5433-5439) — so it is NEVER a blocking conflict and must not scare
        # the user with a default-No "proceed despite conflict?" gate.
        if 5432 in env.port_conflicts:
            print("ℹ️  Port 5432 ถูกใช้งานอยู่ — ไม่ใช่ปัญหา")
            print("   ขั้นตอนถัดไป (เลือก DB) จะตรวจว่ามี PostgreSQL ให้ reuse ไหม")
            print("   ถ้ามี → ใช้ตาม port ที่เจอ; ถ้าไม่มี → เสนอ port ว่างให้เลือก")
            print("   (กด Enter รับค่าที่เสนอ — wizard ไม่เลือก port เองโดยไม่ถาม)")
            print("   ทั้งสองทางจะตั้ง DB_PORT ใน .env ให้ตรง — ไม่ error ตอน start")
            print()

        # Backend/Frontend dev ports only matter when you later run the dev
        # server, not during setup itself. Warn, but don't block (default Yes).
        dev_conflicts = [p for p in env.port_conflicts if p != 5432]
        if dev_conflicts:
            print("⚠️  Port (dev server) ต่อไปนี้ถูกใช้งานอยู่:")
            for port in dev_conflicts:
                print(f"   {port} ({REQUIRED_PORTS[port]})")
            print("   • หยุด service ที่ใช้ port นั้น หรือแก้ port ใน docker-compose.yml ภายหลัง")
            print()
            if not _confirm("   ดำเนินการต่อ?", default_yes=True):
                return False

    return True



# ---------------------------------------------------------------
# Step 1b: Choose Database
# ---------------------------------------------------------------


def find_postgres_containers():
    """หา PostgreSQL containers ที่รันอยู่ พร้อม detect pg_user จริง"""
    # ใช้ --format แยก field ชัดเจน ไม่ใช้ | เพราะอาจอยู่ใน image name
    code, out = _run([
        "docker", "ps", "--filter", "status=running",
        "--format", "{{.Names}}\t{{.Image}}\t{{.Ports}}",
    ])
    if code != 0 or not out:
        return []

    containers = []
    for line in out.strip().split("\n"):
        if not line.strip():
            continue
        parts = line.split("\t")
        if len(parts) < 3:
            continue
        name, image, ports = parts[0].strip(), parts[1].strip(), parts[2].strip()

        # กรอง postgres/pgvector เท่านั้น
        if not ("postgres" in image.lower() or "pgvector" in image.lower()):
            continue

        # หา host port ที่ map ไป 5432
        port = 5432
        match = re.search(r":(\d+)->5432", ports)
        if match:
            port = int(match.group(1))

        # Detect postgres superuser จริงจาก container
        pg_user = _detect_pg_user(name)

        containers.append({
            "name": name,
            "image": image,
            "port": port,
            "pg_user": pg_user,
        })

    return containers


def _detect_pg_user(container_name: str) -> str:
    """ลอง connect จริงด้วย user ที่เป็นไปได้ คืน user แรกที่ connect สำเร็จ"""
    candidates = []

    # 1. ดู env ของ container ก่อน (น่าเชื่อถือที่สุด)
    # container_name comes from `docker ps`, but list-form is still safer
    # against an exotic image name that happens to contain shell metachars.
    code, out = _run(["docker", "exec", container_name, "env"])
    if code == 0:
        for line in out.splitlines():
            if line.startswith("POSTGRES_USER="):
                user = line.split("=", 1)[1].strip()
                if user and user not in candidates:
                    candidates.insert(0, user)
            elif line.startswith("PGUSER="):
                user = line.split("=", 1)[1].strip()
                if user and user not in candidates:
                    candidates.insert(0, user)

    # 2. fallback list
    for u in ["postgres", "admin", "root"]:
        if u not in candidates:
            candidates.append(u)

    # 3. ทดสอบ connect จริงทีละ user. List-form bypasses the shell —
    # the 2>&1 in the old string just merged streams, which _run already
    # does via capture_output → stdout+stderr concat.
    for user in candidates:
        code, out = _run(
            ["docker", "exec", container_name, "psql", "-U", user, "-c", "SELECT 1;"]
        )
        if code == 0 and "ERROR" not in out and "fatal" not in out.lower():
            return user

    # ไม่พบ user ที่ใช้ได้
    return ""


def _validate_ident(label: str, value: str) -> str:
    """Validate a PostgreSQL identifier (db / role name).

    Returns the value if valid. Calls sys.exit on rejection — we'd rather
    refuse to run than silently fall back to a less-safe escape. Identifiers
    must match ^[A-Za-z_][A-Za-z0-9_]*$ — this matches both the unquoted
    identifier rules of PostgreSQL and our scaffold's defaults (db_name is
    derived from the project slug with `-` → `_`).

    The constraint is documented at the _ask_db_credentials prompt (F1).
    """
    if not _IDENT_RE.match(value):
        print(f"   ❌ ค่า '{label}' ไม่ถูกต้อง: {value!r}")
        print(f"      ต้องขึ้นต้นด้วยตัวอักษรหรือ '_' ตามด้วย [A-Za-z0-9_] เท่านั้น")
        print(f"      (PostgreSQL identifier — กรุณาแก้แล้วรันใหม่)")
        sys.exit(1)
    return value


def _sql_quote_literal(value: str) -> str:
    """Escape a string literal for PostgreSQL — double single-quotes.

    Refuses backslashes outright; the standard_conforming_strings default
    means \\ is literal, but mixing this with E'...' strings elsewhere is
    a footgun. Passwords with `\\` need the user to pick a different one.
    """
    if "\\" in value:
        print("   ❌ Password มี '\\' — กรุณาเลือกค่าที่ไม่มี backslash")
        sys.exit(1)
    return value.replace("'", "''")


def _prompt_pg_superuser_password(pg_user: str) -> str:
    """Prompt for the postgres superuser password, then return it.

    Used only when PGPASSWORD is not already set in the env. We pass the
    captured value via env to subprocess.run so psql doesn't try to read
    its own tty prompt (which would deadlock under capture_output) — F3.
    """
    print(f"   🔐 psql connection ต้องการ password ของ superuser '{pg_user}'")
    try:
        # Echo '*' per char — stdlib getpass shows nothing on Windows and
        # users assume the wizard is hung when typing seems invisible.
        return _getpass_masked(f"      Password for {pg_user} (mask): ")
    except (KeyboardInterrupt, EOFError):
        print()
        print("   ❌ ยกเลิก — กรุณาตั้ง PGPASSWORD แล้วรันใหม่ หรือสร้าง user/database ด้วยมือ")
        sys.exit(1)


# SQL templates for the temp-file-based path (F1).
# We use psql -v variables which psql escapes server-side: `:'name'` is a
# literal (single-quoted, with escapes), `:"name"` is an identifier
# (double-quoted, with escapes). This is the canonical way to pass
# untrusted strings to psql without shell or SQL injection.
_CREATE_USER_SQL = r"""\
\set ON_ERROR_STOP on
SELECT EXISTS(SELECT 1 FROM pg_roles WHERE rolname = :'db_user') AS user_exists
\gset
\if :user_exists
    \echo 'EXISTS_USER'
\else
    CREATE USER :"db_user" WITH PASSWORD :'db_password';
    \echo 'CREATED_USER'
\endif
"""

_CREATE_DB_SQL = r"""\
\set ON_ERROR_STOP on
SELECT EXISTS(SELECT 1 FROM pg_database WHERE datname = :'db_name') AS db_exists
\gset
\if :db_exists
    \echo 'EXISTS_DB'
\else
    CREATE DATABASE :"db_name" OWNER :"db_user";
    \echo 'CREATED_DB'
\endif
"""

_GRANT_SQL = r"""\
\set ON_ERROR_STOP on
GRANT ALL PRIVILEGES ON DATABASE :"db_name" TO :"db_user";
"""

_CREATE_EXTENSION_SQL = r"""\
\set ON_ERROR_STOP on
CREATE EXTENSION IF NOT EXISTS :"ext_name";
"""


def _run_psql_script(
    psql_path: str,
    base_args: list[str],
    sql: str,
    variables: dict[str, str],
    env: dict[str, str] | None = None,
    db_name: str | None = None,
) -> tuple[int, str]:
    """Write `sql` to a temp file and run `psql -f <file>` with `-v` variables.

    Returns (returncode, combined-stdout+stderr). Caller inspects the
    output for the sentinel strings produced by `\\echo` in the script.

    Why temp file (not -c): -c is a single statement string that goes
    through the shell — any single quote in db_password / db_user (and
    any non-ascii) requires layered escaping. -f reads the script as a
    file (no shell involvement) and -v values are escaped server-side by
    psql when referenced as `:'name'` / `:"name"`.
    """
    fd, path = tempfile.mkstemp(suffix=".sql", text=True)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(sql)
        cmd_parts = [f'"{psql_path}"'] + base_args
        if db_name:
            cmd_parts.append(f'-d "{db_name}"')
        for key, val in variables.items():
            # psql -v key=value — psql parses the right-hand side itself;
            # the shell still sees this whole arg, so we wrap in quotes
            # and escape any embedded double-quote.
            safe = val.replace('"', '\\"')
            cmd_parts.append(f'-v {key}="{safe}"')
        cmd_parts.extend(["-f", f'"{path}"'])
        return _run(" ".join(cmd_parts), env=env)
    finally:
        try:
            os.unlink(path)
        except OSError:
            pass


def _create_database_native(pg_user: str, db_name: str,
                            db_user: str, db_password: str,
                            host: str = "localhost", port: int = 5432) -> bool:
    """Create user + database via host-side psql against a native PostgreSQL.

    Uses temp SQL files + psql -v server-side quoting (F1) to avoid shell /
    SQL injection through db_password / db_user / db_name. Existence
    checks use `psql -tA` + `SELECT EXISTS(...)` returning literally 't'
    or 'f' (F2). Prompts for PGPASSWORD when not set and forwards it via
    subprocess env (F3) so psql doesn't try to read its own tty under
    capture_output.

    Mirrors _create_database_in_container but uses `psql` on the host
    instead of `docker exec ... psql`. Requires `psql` on PATH (Windows
    installer adds C:\\Program Files\\PostgreSQL\\<ver>\\bin to PATH).

    Returns False if psql is missing or connect fails — caller prints
    fallback instructions.
    """
    import shutil

    psql = shutil.which("psql")
    if not psql:
        print("   ⚠️  psql not on PATH — ข้ามการสร้าง user/database อัตโนมัติ")
        print("      เพิ่ม C:\\Program Files\\PostgreSQL\\<ver>\\bin ลงใน PATH")
        print(f"      แล้วสร้างเองด้วย: psql -U {pg_user} -h {host} -p {port}")
        return False

    # F1: validate identifiers. psql escapes :"name" but identifiers with
    # `"` or non-ASCII cause confusing failures later — fail fast here.
    _validate_ident("pg_user", pg_user)
    _validate_ident("db_user", db_user)
    _validate_ident("db_name", db_name)

    # F3: ensure PGPASSWORD is set before any capture_output psql call,
    # otherwise psql blocks reading from its own tty (which is the
    # captured pipe) → infinite hang.
    env = os.environ.copy()
    if not env.get("PGPASSWORD"):
        env["PGPASSWORD"] = _prompt_pg_superuser_password(pg_user)

    base_args = [
        f"-U {pg_user}",
        f"-h {host}",
        f"-p {port}",
        "-w",  # never prompt for password — PGPASSWORD is set, or fail
    ]

    print(f"   🔍 ทดสอบ connection: native PostgreSQL host={host}:{port} user={pg_user}...")
    code, out = _run(
        f'"{psql}" {" ".join(base_args)} -tA -c "SELECT 1;"',
        env=env,
    )
    if code != 0 or "ERROR" in out or "fatal" in out.lower():
        print(f"   ❌ Connect ไม่ได้ด้วย user '{pg_user}'")
        print(f"      Error: {out[:200]}")
        return False
    print(f"   ✅ Connect สำเร็จ (superuser: {pg_user})")

    # CREATE USER — F2: existence check via `psql -tA -c "SELECT EXISTS(...)"`
    # returning exactly 't' or 'f' on stdout. Old code used `if "1" in out`
    # which tripped on stray stderr digits.
    user_exists_cmd = (
        f'"{psql}" {" ".join(base_args)} -tA -v db_user="{db_user}" '
        f'-c "SELECT EXISTS(SELECT 1 FROM pg_roles WHERE rolname = :\'db_user\');"'
    )
    code, out = _run(user_exists_cmd, env=env)
    if code == 0 and out.strip() == "t":
        print(f"   ✅ User '{db_user}' มีอยู่แล้ว")
    else:
        code, out = _run_psql_script(
            psql, base_args, _CREATE_USER_SQL,
            {"db_user": db_user, "db_password": db_password},
            env=env,
        )
        if code != 0 or "ERROR" in out:
            print(f"   ❌ สร้าง user ล้มเหลว: {out[:200]}")
            return False
        print(f"   ✅ สร้าง user '{db_user}' เสร็จ")

    # CREATE DATABASE
    db_exists_cmd = (
        f'"{psql}" {" ".join(base_args)} -tA -v db_name="{db_name}" '
        f'-c "SELECT EXISTS(SELECT 1 FROM pg_database WHERE datname = :\'db_name\');"'
    )
    code, out = _run(db_exists_cmd, env=env)
    if code == 0 and out.strip() == "t":
        print(f"   ✅ Database '{db_name}' มีอยู่แล้ว")
    else:
        code, out = _run_psql_script(
            psql, base_args, _CREATE_DB_SQL,
            {"db_name": db_name, "db_user": db_user},
            env=env,
        )
        if code != 0 or "ERROR" in out:
            print(f"   ❌ สร้าง database ล้มเหลว: {out[:300]}")
            return False
        print(f"   ✅ สร้าง database '{db_name}' เสร็จ")

    _run_psql_script(
        psql, base_args, _GRANT_SQL,
        {"db_name": db_name, "db_user": db_user},
        env=env,
    )

    # Extensions (require superuser; CREATE EXTENSION lives inside the new DB)
    extensions = ["uuid-ossp", "pgcrypto", "pg_trgm", "vector"]
    ok_exts, fail_exts = [], []
    for ext in extensions:
        code, out = _run_psql_script(
            psql, base_args, _CREATE_EXTENSION_SQL,
            {"ext_name": ext},
            env=env,
            db_name=db_name,
        )
        if code == 0 and "ERROR" not in out:
            ok_exts.append(ext)
        else:
            fail_exts.append(ext)
    if ok_exts:
        print(f"   ✅ Extensions: {', '.join(ok_exts)}")
    if fail_exts:
        print(f"   ⚠️  Extensions ไม่สำเร็จ: {', '.join(fail_exts)}")
    return True


def _docker_exec_psql_script(
    container_name: str, pg_user: str,
    sql: str, variables: dict[str, str],
    db_name: str | None = None,
) -> tuple[int, str]:
    """Run a SQL script inside a docker container's psql via stdin.

    Mirrors _run_psql_script but for the container variant — we pipe the
    script through `docker exec -i ... psql -f -` so the SQL never goes
    through a shell command-line. Variables are passed via psql -v and
    quoted server-side (`:'name'` / `:"name"`).

    Why stdin (not -c with a heredoc): keeps the same safety property as
    the native path — no untrusted string is ever interpolated into a
    shell command line.
    """
    cmd = ["docker", "exec", "-i", container_name, "psql", "-U", pg_user, "-w"]
    if db_name:
        cmd.extend(["-d", db_name])
    for key, val in variables.items():
        cmd.extend(["-v", f"{key}={val}"])
    cmd.extend(["-f", "-"])
    # subprocess.run with a list arg avoids shell interpolation entirely.
    # No shell=True here — that's the whole point.
    try:
        result = subprocess.run(
            cmd,
            input=sql,
            capture_output=True, text=True,
            encoding="utf-8", errors="replace",
        )
    except FileNotFoundError:
        return 127, "docker not found"
    return result.returncode, (result.stdout + result.stderr).strip()


def _create_database_in_container(container_name: str, pg_user: str,
                                   db_name: str, db_user: str,
                                   db_password: str) -> bool:
    """Create dedicated user + database inside a running postgres container.

    Uses `docker exec -i ... psql -f -` with psql -v server-side quoting
    (F1) so db_password / db_user / db_name never get interpolated into
    a shell command. Existence checks use `SELECT EXISTS(...)` returning
    literally 't' / 'f' (F2).

    pg_user  = superuser สำหรับสร้าง (เช่น postgres)
    db_user  = dedicated user สำหรับ app นี้โดยเฉพาะ
    db_password = password ของ db_user
    """
    # F1: validate identifiers.
    _validate_ident("pg_user", pg_user)
    _validate_ident("db_user", db_user)
    _validate_ident("db_name", db_name)

    # Step 1: ทดสอบ connect ด้วย superuser ก่อน
    print(f"   🔍 ทดสอบ connection: {container_name} user={pg_user}...")
    code, out = _run(
        f'docker exec {container_name} psql -U {pg_user} -tA -c "SELECT 1;"'
    )
    if code != 0 or "ERROR" in out or "fatal" in out.lower():
        print(f"   ❌ Connect ไม่ได้ด้วย user '{pg_user}'")
        print(f"      Error: {out[:200]}")
        return False
    print(f"   ✅ Connect สำเร็จ (superuser: {pg_user})")

    # Step 2: สร้าง dedicated user ถ้ายังไม่มี — F2: SELECT EXISTS → 't'/'f'
    code, out = _docker_exec_psql_script(
        container_name, pg_user,
        "\\set ON_ERROR_STOP on\n"
        "SELECT EXISTS(SELECT 1 FROM pg_roles WHERE rolname = :'db_user');\n",
        {"db_user": db_user},
    )
    # `psql -f -` prints a header — find the data row 't' or 'f'.
    user_exists = code == 0 and any(
        line.strip() == "t" for line in out.splitlines()
    )
    if user_exists:
        print(f"   ✅ User '{db_user}' มีอยู่แล้ว")
    else:
        code, out = _docker_exec_psql_script(
            container_name, pg_user, _CREATE_USER_SQL,
            {"db_user": db_user, "db_password": db_password},
        )
        if code != 0 or "ERROR" in out:
            print(f"   ❌ สร้าง user ล้มเหลว: {out[:200]}")
            return False
        print(f"   ✅ สร้าง user '{db_user}' เสร็จ")

    # Step 3: สร้าง database เจ้าของเป็น db_user
    code, out = _docker_exec_psql_script(
        container_name, pg_user,
        "\\set ON_ERROR_STOP on\n"
        "SELECT EXISTS(SELECT 1 FROM pg_database WHERE datname = :'db_name');\n",
        {"db_name": db_name},
    )
    db_exists = code == 0 and any(
        line.strip() == "t" for line in out.splitlines()
    )
    if db_exists:
        print(f"   ✅ Database '{db_name}' มีอยู่แล้ว")
    else:
        code, out = _docker_exec_psql_script(
            container_name, pg_user, _CREATE_DB_SQL,
            {"db_name": db_name, "db_user": db_user},
        )
        if code != 0 or "ERROR" in out:
            print(f"   ❌ สร้าง database ล้มเหลว: {out[:300]}")
            return False
        print(f"   ✅ สร้าง database '{db_name}' เสร็จ")

    # Step 4: Grant privileges
    _docker_exec_psql_script(
        container_name, pg_user, _GRANT_SQL,
        {"db_name": db_name, "db_user": db_user},
    )

    # Step 5: Extensions (ต้องใช้ superuser)
    extensions = ["uuid-ossp", "pgcrypto", "pg_trgm", "vector"]
    ok_exts, fail_exts = [], []
    for ext in extensions:
        code, out = _docker_exec_psql_script(
            container_name, pg_user, _CREATE_EXTENSION_SQL,
            {"ext_name": ext},
            db_name=db_name,
        )
        if code == 0 and "ERROR" not in out:
            ok_exts.append(ext)
        else:
            fail_exts.append(ext)

    if ok_exts:
        print(f"   ✅ Extensions: {', '.join(ok_exts)}")
    if fail_exts:
        print(f"   ⚠️  Extensions ไม่สำเร็จ: {', '.join(fail_exts)}")

    return True


def _prompt_identifier(question: str, default: str) -> str:
    """Prompt for a PostgreSQL identifier (DB / role name).

    Re-prompts until input matches ^[A-Za-z_][A-Za-z0-9_]*$ — same constraint
    enforced server-side by _validate_ident before we compose any SQL (F1).
    Documented here so users hit the message at prompt time, not later
    inside _create_database_*.
    """
    while True:
        value = _prompt(question, default=default)
        if _IDENT_RE.match(value):
            return value
        print(f"   ⚠️  '{value}' ไม่ใช่ PostgreSQL identifier ที่ใช้ได้")
        print(f"      ต้องขึ้นต้นด้วยตัวอักษรหรือ '_' ตามด้วย [A-Za-z0-9_] เท่านั้น")


def _ask_db_credentials(default_db_name: str) -> dict:
    """ถามและให้แก้ไข DB name / user / password ก่อนสร้าง.

    Identifier constraint (db_name / db_user, F1):
        ต้องขึ้นต้นด้วยตัวอักษรหรือ '_' ตามด้วย [A-Za-z0-9_] เท่านั้น —
        psql ใช้ค่านี้สร้าง role / database จริง ๆ ค่าที่ผิด regex จะถูก
        ปฏิเสธก่อน compose SQL (กัน SQL injection / shell injection).

    Password rules (F1):
        - ห้ามมี backslash (`\\`) — ปฏิเสธทันทีเพื่อกัน escape ที่ซับซ้อน.
        - Single quote `'` รับได้ — escape เป็น `''` ตอน compose SQL.
    """
    # สร้าง short name จาก default (ตัด _portal, _system, _app ออก)
    short = default_db_name
    for suffix in ["_executive_intelligence_portal", "_intelligence_portal",
                   "_executive_portal", "_portal", "_system", "_app", "_api"]:
        if short.endswith(suffix):
            short = short[:-len(suffix)]
            break
    # ตัดให้สั้นลง ไม่เกิน 20 chars
    if len(short) > 20:
        short = short[:20].rstrip("_")

    # Generate a unique dev password per scaffold run so two projects on the
    # same dev host never collide on a shared static credential.
    generated_password = _gen_dev_db_password()

    print()
    print("   ค่า default (กด Enter เพื่อใช้):")
    print(f"   DB Name:     {default_db_name}")
    print(f"   DB User:     {short}")
    print(f"   DB Password: {generated_password}  (random, สำหรับ dev เท่านั้น)")
    print()

    if not _confirm("   แก้ไขค่าเหล่านี้?", default_yes=False):
        return {
            "db_name": default_db_name,
            "db_user": short,
            "db_password": generated_password,
        }

    print()
    # Identifier: validate (F1) — refuse anything outside [A-Za-z_][A-Za-z0-9_]*
    db_name = _prompt_identifier("   DB Name", default=default_db_name)
    db_user = _prompt_identifier("   DB User", default=short)
    # Password: reject backslashes (F1) — see _sql_quote_literal docstring.
    while True:
        db_password = _prompt("   DB Password", default=generated_password)
        if "\\" not in db_password:
            break
        print("   ⚠️  Password มี '\\' — กรุณาเลือกค่าที่ไม่มี backslash")

    return {
        "db_name": db_name,
        "db_user": db_user,
        "db_password": db_password,
    }


def choose_existing_database(default_db_name: str) -> dict:
    """Collect an existing database connection without modifying its schema."""
    print()
    print("── Existing Database ─────────────────────────────────────")
    print()
    print("   โหมดนี้จะตั้งค่า connection เท่านั้น")
    print("   • ไม่สร้าง user/database")
    print("   • ไม่รัน migration หรือ seed อัตโนมัติ")
    print("   • ไม่แก้/ลบ table เดิม")
    print()

    host = _prompt("   DB Host", default="localhost")
    while True:
        raw_port = _prompt("   DB Port", default="5432")
        try:
            port = int(raw_port)
        except ValueError:
            print("   ⚠️  port ต้องเป็นตัวเลข")
            continue
        if 1 <= port <= 65535:
            break
        print("   ⚠️  port ต้องอยู่ระหว่าง 1-65535")

    db_name = _prompt("   DB Name", default=default_db_name)
    db_user = _prompt("   DB User")
    db_password = _getpass_masked("   DB Password: ")

    return {
        "skip": False,
        "database_mode": "existing",
        "existing_database": True,
        "skip_schema_setup": True,
        "host": host,
        "port": port,
        "db_name": db_name,
        "db_user": db_user,
        "db_password": db_password,
    }


def choose_database(
    default_db_name: str,
    env: EnvCheck | None = None,
    auth_required: bool = False,
) -> dict:
    print()
    print("── Database ──────────────────────────────────────────────")
    print()

    # Login ต้องใช้ DB (users / roles / permissions / app_settings / sessions).
    # ถ้า wizard ก่อนหน้านี้ตอบว่าใช้ auth → ห้ามข้าม DB เพราะ project จะ boot
    # ไม่ติดและ login เป็นไปไม่ได้
    if auth_required:
        print("   🔐 Login เปิดใช้งานอยู่ — Database จำเป็น (users / roles / sessions)")
        print("      จะตั้งค่า DB อัตโนมัติ")
        print()
    else:
        need_db = _confirm("   Project นี้ต้องการ Database ไหม?", default_yes=True)
        if not need_db:
            print("   ⏭️  ข้าม Database setup")
            return {"skip": True}
        print()

    # Branch: Docker engine off + native PostgreSQL on 5432
    # → skip find_postgres_containers (would crash / return empty without engine)
    # → route directly to "use native pg" path
    if env is not None and not env.docker_engine_ok and env.native_pg_on_5432:
        print("   พบ PostgreSQL native บนพอร์ต 5432 (Docker Engine ไม่ได้รัน)")
        print("   จะใช้ native PostgreSQL แทน Docker container")
        print()
        pg_user = _prompt("   PostgreSQL superuser (สำหรับสร้าง DB)",
                          default="postgres", required=True)
        creds = _ask_db_credentials(default_db_name)
        return {
            "skip": False,
            "use_existing": True,
            "native": True,  # marker: no docker exec, connect via host
            "host": "localhost",
            "port": 5432,
            "pg_user": pg_user,
            **creds,
        }

    containers = find_postgres_containers()

    if not containers:
        print("   ไม่พบ PostgreSQL containers ที่รันอยู่")
        print("   จะสร้าง Docker container ใหม่ให้อัตโนมัติ")
        new_port = _ask_new_container_port(env)
        creds = _ask_db_credentials(default_db_name)
        return {"skip": False, "use_existing": False,
                "host": "localhost", "port": new_port,
                "pg_user": "postgres", **creds}

    print("   พบ PostgreSQL containers ที่รันอยู่:")
    print()
    for i, c in enumerate(containers, 1):
        pg_user_display = c["pg_user"] if c["pg_user"] else "ไม่ทราบ"
        print(f"   {i}. {c['name']}  (port {c['port']}, user: {pg_user_display})")
    print(f"   {len(containers)+1}. สร้าง Docker container ใหม่")
    print()
    print("   💡 แนะนำเลือก container เดิม — จะสร้าง dedicated user+database ใหม่ใน container นั้น")
    print()

    while True:
        choice = input(f"   เลือก [1-{len(containers)+1}] (default: 1): ").strip() or "1"
        try:
            idx = int(choice) - 1
            if idx == len(containers):
                new_port = _ask_new_container_port(env)
                creds = _ask_db_credentials(default_db_name)
                return {"skip": False, "use_existing": False,
                        "host": "localhost", "port": new_port,
                        "pg_user": "postgres", **creds}
            elif 0 <= idx < len(containers):
                c = containers[idx]
                creds = _ask_db_credentials(default_db_name)
                return {
                    "skip": False,
                    "use_existing": True,
                    "host": "localhost",
                    "port": c["port"],
                    "container_name": c["name"],
                    "pg_user": c["pg_user"],  # superuser สำหรับสร้าง DB
                    **creds,
                }
        except ValueError:
            pass
        print("   กรุณาเลือกตัวเลขที่ถูกต้อง")

# ───────────────────────────────────────────────────────────────
# Step 2: Collect config (ถามแค่ 2 อย่าง)
# ───────────────────────────────────────────────────────────────


@dataclass
class ProjectConfig:
    project_slug: str = ""
    project_display_name: str = ""
    auth_scope: str = "both"
    maturity_level: str = "L1"  # L0 | L1 | L2 | L3 (AGENTS.md §13)
    stack_variant: str = "default"  # default | next-js | htmx | streamlit | timescale
    default_language: str = "th"
    # Opt-in Database Connections + Query Sandbox module (docs/patterns/
    # db-connections.md). When True the scaffold emits the module + sets the
    # FEATURE_DB_CONNECTIONS flag; the operator must also generate a Fernet key.
    feature_db_connections: bool = False
    owner: str = ""  # CT extension — Registry ownership
    bu: str = ""  # CT extension — Business Unit
    registry_url: str = ""  # empty = skip registration (opt-in)
    jwt_secret_key: str = field(default="")
    # AES-256 key for Auth module MFA TOTP secrets at rest (32-byte hex).
    # Generated even when auth isn't enabled yet — keeps the value stable
    # for the project's lifetime so enabling MFA later doesn't break any
    # future enrolment.
    mfa_encryption_key: str = field(default="")

    # Bootstrap super-admin (asked when auth_scope is set). Email is written
    # to .env via AUTH_BOOTSTRAP_SUPER_ADMIN_EMAIL; auth_type chooses how the
    # first user authenticates. initial_password is transient — passed to
    # seed via env var AUTH_BOOTSTRAP_INITIAL_PASSWORD, never persisted.
    bootstrap_admin_email: str = ""
    bootstrap_admin_auth_type: str = "sso"  # "sso" | "local"
    bootstrap_initial_password: str = ""  # only used when auth_type == "local"

    def __post_init__(self) -> None:
        if not self.jwt_secret_key:
            self.jwt_secret_key = secrets.token_hex(32)
        if not self.mfa_encryption_key:
            self.mfa_encryption_key = secrets.token_hex(32)


_EMAIL_RE = re.compile(r"^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$")


def _prompt_bootstrap_super_admin(cfg: ProjectConfig) -> None:
    """Ask for the first super-admin so seed.py can create the user.

    Internal-only / both → SSO is the natural default (Azure AD users
    auto-provision via JWKS verify; seed pre-creates the row + role).
    External-only → forces local auth + a real password (one-shot via
    env var AUTH_BOOTSTRAP_INITIAL_PASSWORD; never persisted).
    """
    print("── Bootstrap Super Admin ─────────────────────────────────")
    print()
    print("   user แรกของระบบ (role internal:super_admin)")
    print("   เปิดสิทธิ์ admin ทั้งหมด รวมถึงเพิ่ม role/user คนอื่น")
    print()

    while True:
        email = input("   Super admin email: ").strip()
        if not email:
            print("   ⚠️  จำเป็นต้องระบุ — admin คนแรกใช้สำหรับ login ครั้งแรก")
            continue
        if not _EMAIL_RE.match(email):
            print("   ⚠️  รูปแบบ email ไม่ถูกต้อง")
            continue
        cfg.bootstrap_admin_email = email.lower()
        break

    # Auth type — pick the default that GUARANTEES the admin can log in for
    # the chosen scope, so a user accepting defaults never locks themselves out:
    #   external_only → local  (SSO isn't available; seed enables local)
    #   internal_only → SSO     (seed disables local — a local admin would hit
    #                            "Local authentication is disabled" at /login)
    #   both          → local   (both enabled; local works without Azure config)
    if cfg.auth_scope == "external_only":
        cfg.bootstrap_admin_auth_type = "local"
        print("   Auth type:  local (external_only scope)")
    elif cfg.auth_scope == "internal_only":
        cfg.bootstrap_admin_auth_type = "sso"
        print("   Auth type:  SSO / Azure AD (internal_only scope)")
        print("   ⚠️  ต้องตั้งค่า Azure AD (client id/secret/tenant) ใน backend/.env")
        print("       ก่อน ไม่งั้น login ไม่ได้ — internal_only ปิด email/password ไว้")
    else:
        print()
        print("   Auth type ของ super admin:")
        print("     1. Local  — email + password (login ได้ทันที ไม่ต้องตั้ง Azure AD)")
        print("     2. SSO    — Azure AD (สำหรับ production ที่ตั้ง Azure AD แล้ว)")
        print()
        while True:
            t = input("   เลือก [1-2] (default: 1 Local): ").strip() or "1"
            if t == "1":
                cfg.bootstrap_admin_auth_type = "local"
                break
            if t == "2":
                cfg.bootstrap_admin_auth_type = "sso"
                break
            print("   ⚠️  กรุณาเลือก 1 หรือ 2")

    # Initial password (local only) — masked input shows '*' per char so the
    # user can tell typing is registering (stdlib getpass shows nothing).
    if cfg.bootstrap_admin_auth_type == "local":
        print()
        print("   Initial password สำหรับ super admin (≥ 12 ตัว, แสดง * ขณะพิมพ์)")
        print("   • ต้องผสม ≥ 2 ใน 4: ตัวพิมพ์ใหญ่ / เล็ก / ตัวเลข / สัญลักษณ์")
        print("   • ห้ามเป็นตัวอักษรล้วน/เลขล้วน, ลำดับ (123456789012), password ยอดฮิต")
        print("   • ใช้ครั้งเดียวตอน seed; ไม่ commit; เปลี่ยนได้ทันที่ login ครั้งแรก")
        # email local-part + project slug ห้ามโผล่ใน password (เดาง่ายสำหรับ deploy นี้)
        context_terms = [cfg.bootstrap_admin_email.split("@", 1)[0], cfg.project_slug]
        while True:
            pw = _getpass_masked("   Password: ")
            err = password_strength_error(pw, context_terms=context_terms)
            if err:
                print(f"   ⚠️  {err}")
                continue
            pw2 = _getpass_masked("   ยืนยัน password: ")
            if pw != pw2:
                print("   ⚠️  Password ไม่ตรงกัน — ลองใหม่")
                continue
            cfg.bootstrap_initial_password = pw
            break

    print()


def collect_config(root: Path) -> ProjectConfig:
    print("─" * 60)
    print()

    cfg = ProjectConfig()

    # ── ชื่อ project — auto-detect จาก folder name
    folder_name = root.name
    suggested_slug = _slug_from_folder(folder_name)
    suggested_display = folder_name.replace("-", " ").replace("_", " ").title()

    print(f"📁 Folder: {folder_name}")
    print(f"   ชื่อที่แนะนำ: {suggested_slug}")
    print()

    if _confirm(f"   ใช้ชื่อ '{suggested_slug}'?", default_yes=True):
        cfg.project_slug = suggested_slug
        cfg.project_display_name = suggested_display
    else:
        cfg.project_slug = _prompt(
            "   Project slug (lowercase, kebab-case)",
            default=suggested_slug,
        )
        cfg.project_display_name = _prompt(
            "   Display name",
            default=suggested_display,
        )

    print()

    # ── ประเภท user
    print("── ประเภท User ───────────────────────────────────────────")
    print()
    print("   1. Internal only  — พนักงาน Chia Tai (Azure AD)")
    print("   2. External only  — vendor / customer (email + password)")
    print("   3. Both           — ทั้งสองประเภท")
    print()
    print("   💡 Keys ทุกตัว (Azure AD, Claude API) จะว่างไว้ก่อน")
    print("      เพิ่มได้ทีหลังใน backend/.env เมื่อพร้อม")
    print()

    while True:
        choice = input("   เลือก [1-3] (default: 3): ").strip() or "3"
        if choice == "1":
            cfg.auth_scope = "internal_only"
            break
        elif choice == "2":
            cfg.auth_scope = "external_only"
            break
        elif choice == "3":
            cfg.auth_scope = "both"
            break
        print("   ⚠️  กรุณาเลือก 1, 2 หรือ 3")

    print()

    # ── Bootstrap super admin (only when auth is in scope)
    _prompt_bootstrap_super_admin(cfg)

    # ── Maturity level (v3.0)
    print("── Maturity Level (AGENTS.md §13) ────────────────────────")
    print()
    print("   L0 Prototype        — < 3 เดือน / < 10 users / MVP")
    print("   L1 Internal Tool    — stable, single BU, < 50 users (DEFAULT)")
    print("   L2 Business-Critical — multi-BU, mission-critical")
    print("   L3 External/Regulated — vendor/customer-facing, PDPA scope")
    print()
    while True:
        ml = input("   เลือก [L0/L1/L2/L3] (default: L1): ").strip().upper() or "L1"
        if ml in ("L0", "L1", "L2", "L3"):
            cfg.maturity_level = ml
            break
        print("   ⚠️  กรุณาเลือก L0, L1, L2 หรือ L3")
    print()

    # ── Stack variant (v3.0) — most projects use default
    print("── Stack Variant (AGENTS.md §A) ──────────────────────────")
    print()
    print("   1. default     — FastAPI + React/Vite (DEFAULT)")
    print("                    ใช้กับ: internal CRUD, dashboard, standard web app")
    print("   2. next-js     — Next.js 15+ + FastAPI BFF")
    print("                    ใช้กับ: public site ที่ต้อง SEO/SSR (vendor/customer-facing)")
    print("   3. htmx        — FastAPI + HTMX + Jinja")
    print("                    ใช้กับ: tiny internal tool < 5 หน้า ไม่ต้องการ SPA")
    print("   4. streamlit   — Streamlit / Gradio (L0 only)")
    print("                    ใช้กับ: AI prototype < 1 เดือน — ต้อง refactor ถ้าขึ้น L1")
    print("   5. timescale   — Default + TimescaleDB")
    print("                    ใช้กับ: heavy time-series (sensor, IoT, telemetry, metrics)")
    print()
    while True:
        sv_choice = input("   เลือก [1-5] (default: 1): ").strip() or "1"
        sv_map = {"1": "default", "2": "next-js", "3": "htmx", "4": "streamlit", "5": "timescale"}
        if sv_choice in sv_map:
            cfg.stack_variant = sv_map[sv_choice]
            break
        print("   ⚠️  กรุณาเลือก 1-5")
    print()

    # ── Feature Modules — opt-in (default off) ───────────────────────
    print("── Feature Modules ───────────────────────────────────────")
    print()
    print("   Database Connections + Query Sandbox: super_admin ลงทะเบียน")
    print("   external PostgreSQL ผ่าน UI แล้วรัน SQL (read-only by default)")
    print("   พร้อม audit log — เปิดเฉพาะเมื่อ project ต้องต่อ DB ภายนอก")
    cfg.feature_db_connections = _confirm(
        "   เปิดใช้งาน Database Connections module?", default_yes=False
    )
    if cfg.feature_db_connections:
        print("   ⚠️  ต้องสร้าง Fernet key แล้วตั้ง DB_CONNECTIONS_ENCRYPTION_KEY ใน")
        print("       backend/.env ก่อนใช้งาน (ดู docs/patterns/db-connections.md):")
        print("       python -c \"from cryptography.fernet import Fernet; "
              "print(Fernet.generate_key().decode())\"")
    print()

    # ── CT App Registry — opt-in (required at L3, optional elsewhere)
    print("── CT App Registry ───────────────────────────────────────")
    print()
    if cfg.maturity_level == "L3":
        print("   L3 project — Registry registration required.")
        cfg.registry_url = _prompt(
            "   Registry URL",
            default="https://ctappregistry.chiataigroup.com",
            required=True,
        )
    else:
        print(f"   {cfg.maturity_level} project — Registry registration is optional.")
        print("   (Track in central catalog + daily telemetry push. Skip if unsure.)")
        if _confirm("   ลงทะเบียนกับ CT App Registry?", default_yes=False):
            cfg.registry_url = _prompt(
                "   Registry URL",
                default="https://ctappregistry.chiataigroup.com",
                required=True,
            )
        else:
            cfg.registry_url = ""
            print("   ⏭️  จะข้าม registration — register ด้วยมือทีหลังได้")
    print()

    # ── Owner + BU (CT extension — Registry tracking)
    print("── Project Owner & Business Unit (CT extension) ─────────")
    print()
    cfg.owner = _prompt("   Owner (ชื่อหรือ email)", required=True)
    print()
    print("   Business Unit:")
    print("   1. Fertilizer")
    print("   2. Crop Protection")
    print("   3. Seed")
    print("   4. Other (ระบุเอง)")
    print()
    while True:
        bu_choice = input("   เลือก [1-4] (default: 4): ").strip() or "4"
        if bu_choice == "1":
            cfg.bu = "fertilizer"
            break
        elif bu_choice == "2":
            cfg.bu = "crop_protection"
            break
        elif bu_choice == "3":
            cfg.bu = "seed"
            break
        elif bu_choice == "4":
            cfg.bu = _prompt("   ระบุ Business Unit", default="other")
            break
        print("   ⚠️  กรุณาเลือก 1-4")

    print()
    return cfg


# ───────────────────────────────────────────────────────────────
# Step 3: Generate files
# ───────────────────────────────────────────────────────────────


def generate_files(cfg: ProjectConfig, root: Path, db_choice: dict | None = None) -> None:
    print("── Generate files ────────────────────────────────────────")
    print()

    slug = cfg.project_slug
    db_name = slug.replace("-", "_")
    db_port = db_choice.get("port", 5432) if db_choice else 5432

    # db_name, db_user, db_password มาจาก _ask_db_credentials ที่ผู้ใช้ยืนยันแล้ว.
    # Fallback ใช้ random password เผื่อ caller skip wizard เพื่อกัน static credential
    # บน projects ที่ถูก scaffold ทั้งหมด (audit finding #1).
    if db_choice and not db_choice.get("skip"):
        db_name = db_choice.get("db_name", db_name)
        db_user = db_choice.get("db_user", db_name)
        db_password = db_choice.get("db_password") or _gen_dev_db_password()
    else:
        db_user = db_name
        db_password = _gen_dev_db_password()

    database_mode = (
        db_choice.get("database_mode", "new") if db_choice else "new"
    )

    # project.config — see AGENTS.md §10 for contract
    config_content = f"""# project.config — auto-generated by setup.py
# DO NOT commit this file.

PROJECT_SLUG={slug}
PROJECT_DISPLAY_NAME={cfg.project_display_name}

# Maturity (v3.0 — gates Tier 4 patterns; AGENTS.md §13)
MATURITY_LEVEL={cfg.maturity_level}

# Stack variant (v3.0 — set at init only; AGENTS.md §A)
STACK_VARIANT={cfg.stack_variant}

# Database ownership mode: new | existing
DATABASE_MODE={database_mode}

AUTH_SCOPE={cfg.auth_scope}
DEFAULT_LANGUAGE={cfg.default_language}

# Feature Modules (opt-in — default off; docs/patterns/db-connections.md)
FEATURE_DB_CONNECTIONS={str(cfg.feature_db_connections).lower()}

# CT extensions (Registry ownership tracking — not in AGENTS.md §10)
OWNER={cfg.owner}
BU={cfg.bu}
"""
    (root / "project.config").write_text(config_content, encoding="utf-8")
    print("   ✅ project.config")

    # .gitignore — Layout A copies the template's full .gitignore so we only
    # need to append project-specific entries. sibling-zip starts from an
    # empty dir; emit the full ruleset so __pycache__/node_modules/.venv etc.
    # don't get committed by accident.
    gitignore = root / ".gitignore"
    project_entries = "\n# Generated by setup.py\nproject.config\nbackend/.env\nbackend/.env.*\n!backend/.env.example\n!backend/.env.prod.example\nfrontend/.env\nfrontend/.env.*\n!frontend/.env.example\n"
    if gitignore.exists():
        existing = gitignore.read_text(encoding="utf-8")
        if "project.config" not in existing:
            gitignore.write_text(existing + project_entries, encoding="utf-8")
    else:
        base = (
            "# Python\n"
            "__pycache__/\n"
            "*.py[cod]\n"
            "*.egg-info/\n"
            ".pytest_cache/\n"
            ".mypy_cache/\n"
            ".ruff_cache/\n"
            ".venv/\n"
            "venv/\n"
            "\n"
            "# Node\n"
            "node_modules/\n"
            "dist/\n"
            "build/\n"
            "\n"
            "# Editor / OS\n"
            ".vscode/*\n"
            "!.vscode/settings.json\n"
            "!.vscode/extensions.json\n"
            ".idea/\n"
            ".DS_Store\n"
            "Thumbs.db\n"
            "desktop.ini\n"
            "\n"
            "# Claude Code local state\n"
            ".claude/\n"
        )
        gitignore.write_text(base + project_entries, encoding="utf-8")
    print("   ✅ .gitignore")

    # README.md (project-specific)
    readme = f"""# {cfg.project_display_name}

## Quick Start

```bash
python scripts/setup.py
```

- Frontend: http://localhost:5173
- Backend API: http://localhost:8000
- API docs: http://localhost:8000/docs

## Keys ที่ต้องเพิ่มทีหลัง (backend/.env)

```bash
CLAUDE_API_KEY=        # จาก https://console.anthropic.com/
AZURE_AD_CLIENT_SECRET= # จาก Azure Portal (ถ้าใช้ internal users)
```

## Documentation

- [AGENTS.md](AGENTS.md) — technical standard
- [docs/human/onboarding.md](docs/human/onboarding.md) — developer setup
"""
    (root / "README.md").write_text(readme, encoding="utf-8")
    print("   ✅ README.md")

    # backend/.env
    _scaffold_backend(cfg, root, db_port=db_port, db_user=db_user, db_password=db_password)
    if db_choice and db_choice.get("existing_database"):
        _set_env_value(root / "backend" / ".env", "DB_HOST", db_choice["host"])
        _set_env_value(root / "backend" / ".env", "DB_PORT", str(db_choice["port"]))
        _set_env_value(root / "backend" / ".env", "DB_NAME", db_choice["db_name"])
        _set_env_value(root / "backend" / ".env", "DB_USER", db_choice["db_user"])
        _set_env_value(root / "backend" / ".env", "DB_PASSWORD", db_choice["db_password"])
    print("   ✅ backend/ structure")

    # frontend/.env
    _scaffold_frontend(cfg, root)
    print("   ✅ frontend/ structure")

    # docker/ — pass db_port so compose host-port mapping matches what .env
    # tells the backend to dial (otherwise backend will connect-refuse).
    # db_password keeps compose POSTGRES_PASSWORD == backend/.env DB_PASSWORD.
    # Existing-DB credentials belong only in the gitignored backend/.env;
    # never copy them into the tracked local-dev compose file.
    docker_password = (
        _gen_dev_db_password()
        if db_choice and db_choice.get("existing_database")
        else db_password
    )
    _scaffold_docker(cfg, root, db_port=db_port, db_password=docker_password)
    print("   ✅ docker/ structure")

    # Apply opt-in REGISTRY_URL to backend/.env (default in scaffold is empty)
    if cfg.registry_url:
        env_file = root / "backend" / ".env"
        if env_file.exists():
            content = env_file.read_text(encoding="utf-8")
            updated = []
            for line in content.splitlines():
                if line.startswith("REGISTRY_URL="):
                    updated.append(f"REGISTRY_URL={cfg.registry_url}")
                else:
                    updated.append(line)
            env_file.write_text("\n".join(updated) + "\n", encoding="utf-8")
            print(f"   ✅ REGISTRY_URL set ({cfg.registry_url})")

    # pre-commit hooks + custom checks (v3.0)
    _scaffold_tooling(cfg, root)
    print("   ✅ .pre-commit-config.yaml + scripts/checks/")

    # CT global standards (AupModal, etc.) — mandatory per AGENTS.md §18
    _scaffold_global_standards(cfg, root)
    print("   ✅ frontend/src/components/AupModal.tsx (CT global)")

    # Stamp the project so migrate-security.py --check can tell at a glance
    # whether this project is on the latest baseline or needs migration.
    _write_security_baseline(root, source="scaffold")
    print("   ✅ .security-baseline (v3.0.2 scaffold)")

    print()


# ───────────────────────────────────────────────────────────────
# Step 4: Install + Start
# ───────────────────────────────────────────────────────────────


def install_and_start(root: Path, db_choice: dict | None = None) -> bool:
    """Local dev mode:
    - DB ใน Docker (container เดิมหรือใหม่) หรือข้ามถ้าไม่ต้องการ
    - Backend รันบนเครื่อง (uvicorn --reload)
    - Frontend รันบนเครื่อง (npm run dev)
    """
    if db_choice is None:
        db_choice = {"skip": False, "use_existing": False,
                     "host": "localhost", "port": 5432, "pg_user": "postgres"}

    skip_db = db_choice.get("skip", False)

    print("── เริ่มต้น project (Local Dev mode) ────────────────────")
    print()
    if skip_db:
        print("   DB       → ข้าม")
    elif db_choice.get("existing_database"):
        print(
            "   DB       → existing database "
            f"({db_choice['host']}:{db_choice['port']}/{db_choice['db_name']})"
        )
    elif db_choice.get("native"):
        print(f"   DB       → ใช้ native PostgreSQL (host=localhost:{db_choice.get('port', 5432)})")
    elif db_choice.get("use_existing"):
        print(f"   DB       → ใช้ container '{db_choice['container_name']}' (port {db_choice['port']})")
    else:
        print("   DB       → Docker container ใหม่")
    print("   Backend  → local (uvicorn --reload)")
    print("   Frontend → local (npm run dev)")
    print()

    docker_dir = root / "docker"
    backend_dir = root / "backend"
    frontend_dir = root / "frontend"
    db_name = root.name.lower().replace(" ", "_").replace("-", "_")
    db_name = re.sub(r"[^a-z0-9_]", "_", db_name)
    # อ่าน db_name จริงจาก .env
    env_file = backend_dir / ".env"
    if env_file.exists():
        for line in env_file.read_text(encoding="utf-8").splitlines():
            if line.startswith("DB_NAME="):
                db_name = line.split("=", 1)[1].strip()
                break

    # 1. npm install — NON-FATAL. A transient failure (flaky registry, or an
    # OneDrive sync lock on the just-extracted tree) must NOT abort the whole
    # setup and leave a DB-less, un-seedable project: the backend + DB + seed
    # below are what actually gate login, and the frontend deps can be
    # installed later with a plain `npm install`. Retry once, then continue
    # regardless. (Dogfood 2026-06-01: npm failed here → setup returned early
    # → no DB/admin → user stuck at "can't log in".)
    print("   📦 ติดตั้ง frontend dependencies...")
    code = _run_visible(["npm", "install"], cwd=frontend_dir)
    if code != 0:
        print("   ⚠️  npm install รอบแรกไม่ผ่าน — ลองใหม่อีกครั้ง...")
        code = _run_visible(["npm", "install"], cwd=frontend_dir)
    npm_ok = code == 0
    if npm_ok:
        print("   ✅ npm install เสร็จ")
    else:
        print("   ⚠️  npm install ยังไม่ผ่าน — ข้ามไปก่อน (ไม่บล็อก DB/seed)")
        print("      รันเองภายหลัง: cd frontend && npm install")
        print("      ถ้าโปรเจกต์อยู่ใน OneDrive: pause sync ชั่วคราวแล้วลองใหม่")
    print()

    # 2. pip install backend
    print("   🐍 ติดตั้ง backend dependencies...")
    pip_ok = False
    # ใช้ sys.executable เพื่อให้ install ใน Python environment เดียวกับที่รัน script นี้
    # ลอง install แบบ editable ก่อน
    code = _run_visible([sys.executable, "-m", "pip", "install", "-e", ".[dev]"], cwd=backend_dir)
    if code != 0:
        # ถ้าล้มเหลว ลอง install แบบปกติ (ไม่ editable) สำหรับ Anaconda
        print("   ⚠️  Editable install ล้มเหลว — ลอง regular install...")
        code = _run_visible(
            [sys.executable, "-m", "pip", "install",
             "fastapi", "uvicorn[standard]", "pydantic", "pydantic-settings",
             "sqlalchemy[asyncio]", "asyncpg", "alembic", "httpx",
             "python-jose[cryptography]", "passlib[bcrypt]", "msal", "anthropic",
             "structlog", "apscheduler", "prometheus-fastapi-instrumentator", "slowapi"],
            cwd=backend_dir,
        )
    if code == 0:
        pip_ok = True
        print("   ✅ pip install เสร็จ")
    else:
        print("   ❌ pip install ล้มเหลว")
        print("      รันเองด้วย: cd backend && pip install -e .[dev]")
    print()

    # 3. DB — ข้าม / native / ใช้ container เดิม / สร้างใหม่
    if skip_db:
        print("   ⏭️  ข้าม Database setup")
        print()
    elif db_choice.get("existing_database"):
        print("   🛡️  Existing database — ข้าม create/migration/seed อัตโนมัติ")
        print("      ตรวจ model mapping และ migration plan ก่อนแตะ schema เดิม")
        print("      ดู docs/database.md §1.4")
        print()
    elif db_choice.get("native"):
        pg_user = db_choice.get("pg_user", "postgres")
        db_user = db_choice.get("db_user", db_name)
        db_password = db_choice.get("db_password") or _gen_dev_db_password()
        port = db_choice.get("port", 5432)

        print(f"   🗄️  สร้าง user='{db_user}' + database='{db_name}' บน native PostgreSQL...")
        ok = _create_database_native(
            pg_user, db_name, db_user, db_password,
            host="localhost", port=port,
        )
        if not ok:
            print(f"      ตรวจสอบด้วย: psql -U {pg_user} -h localhost -p {port}")
        print()
    elif db_choice.get("use_existing"):
        container = db_choice["container_name"]
        pg_user = db_choice.get("pg_user", "")

        # ถ้า detect user ไม่ได้ — ถามเอง
        if not pg_user:
            print(f"   ⚠️  ไม่สามารถ detect PostgreSQL superuser ของ {container} ได้อัตโนมัติ")
            pg_user = input("      ระบุ PostgreSQL superuser (เช่น postgres): ").strip()
            if not pg_user:
                pg_user = "postgres"

        db_user = db_choice.get("db_user", db_name)
        db_password = db_choice.get("db_password") or _gen_dev_db_password()

        print(f"   🗄️  สร้าง user='{db_user}' + database='{db_name}' ใน {container}...")
        ok = _create_database_in_container(
            container, pg_user, db_name, db_user, db_password
        )
        if not ok:
            print(f"      ตรวจสอบด้วย: docker exec {container} psql -U {pg_user}")
        db_choice["pg_user"] = pg_user
        print()
    else:
        # สร้าง Docker container ใหม่
        print("   🐳 เริ่ม Database container...")
        code = _run_visible(["docker", "compose", "up", "-d", "db"], cwd=docker_dir)
        if code != 0:
            print("   ❌ docker compose up db ล้มเหลว")
            return False
        print("   ✅ DB container กำลังขึ้น...")
        print()

    # 4. รอ DB ready (ข้ามถ้าไม่มี DB หรือ native pg ซึ่งรันอยู่แล้ว)
    if (
        not skip_db
        and not db_choice.get("native")
        and not db_choice.get("existing_database")
    ):
        print("   ⏳ รอ database พร้อม...")
        for i in range(30):
            if db_choice.get("use_existing"):
                code, _ = _run(
                    ["docker", "exec", db_choice["container_name"], "pg_isready"]
                )
            else:
                code, _ = _run(
                    ["docker", "compose", "exec", "db", "pg_isready"],
                    cwd=docker_dir,
                )
            if code == 0:
                print("   ✅ Database พร้อมแล้ว")
                break
            time.sleep(2)
            print(f"      รอ... ({(i+1)*2}s)", end="\r")
        else:
            print("   ⚠️  Database ใช้เวลานาน — รอแล้วรัน migration เอง")
            return False
        print()

    # 5. alembic upgrade head (ข้ามถ้าไม่มี DB)
    if not skip_db and not db_choice.get("skip_schema_setup") and pip_ok:
        print("   🗃️  รัน database migrations...")
        env_copy = os.environ.copy()
        env_copy["DB_HOST"] = "localhost"
        env_copy["DB_PORT"] = str(db_choice.get("port", 5432))
        if db_choice.get("use_existing"):
            env_copy["DB_USER"] = db_choice.get("db_user",
                                    db_choice.get("pg_user", "postgres"))
            env_copy["DB_PASSWORD"] = db_choice.get("db_password", "")
        # ลอง alembic command โดยตรงก่อน ถ้าไม่มีค่อยใช้ python -m.
        # List-form (no shell=True) — audit finding #4: removes the fragile
        # quote-strings-into-shell pattern even when args are trusted today.
        import shutil
        alembic_cmd = shutil.which("alembic")
        if alembic_cmd:
            run_argv = [alembic_cmd, "upgrade", "head"]
        else:
            run_argv = [sys.executable, "-m", "alembic", "upgrade", "head"]
        result = subprocess.run(
            run_argv,
            cwd=backend_dir, env=env_copy,
        )
        if result.returncode != 0:
            print("   ⚠️  Migration ล้มเหลว — รันเองด้วย:")
            print("      cd backend")
            pg_user = db_choice.get("pg_user", "postgres")
            print("      set DB_HOST=localhost")
            print(f"      set DB_PORT={db_choice.get('port', 5432)}")
            print(f"      set DB_USER={pg_user}")
            print("      alembic upgrade head")
        else:
            print("   ✅ Migrations เสร็จ")
            # Auto-seed first super-admin if .env has AUTH_BOOTSTRAP_* set.
            # Without this the user opens /login → 401 because users table
            # is empty (DB has roles/perms/menus but no actual admin row).
            env_path = backend_dir / ".env"
            has_bootstrap = (
                env_path.exists()
                and any(line.startswith("AUTH_BOOTSTRAP_SUPER_ADMIN_EMAIL=") and line.split("=", 1)[1].strip()
                        for line in env_path.read_text(encoding="utf-8").splitlines())
            )
            if has_bootstrap:
                print("   🌱 รัน seed (bootstrap super admin + default roles/perms/menus)...")
                # List-form (no shell=True) — audit finding #4.
                seed_result = subprocess.run(
                    [sys.executable, "-m", "app.seed"],
                    cwd=backend_dir, env=env_copy,
                )
                if seed_result.returncode == 0:
                    print("   ✅ Seed เสร็จ")
                else:
                    print("   ⚠️  Seed ล้มเหลว — รันเองด้วย:")
                    print("      cd backend")
                    print("      set DB_HOST=localhost")
                    print(f"      set DB_PORT={db_choice.get('port', 5432)}")
                    print("      python -m app.seed")
    elif not skip_db and not db_choice.get("skip_schema_setup") and not pip_ok:
        print("   ⏭️  ข้าม migration — pip install ยังไม่สำเร็จ")
        print("      รันเองด้วย:")
        print("      cd backend && pip install -e .[dev]")
        # No space before && — cmd.exe keeps a trailing space in the value
        # otherwise (DB_HOST="localhost ") and asyncpg getaddrinfo fails.
        print(f"      set DB_HOST=localhost&& set DB_PORT={db_choice.get('port', 5432)}&& alembic upgrade head")
    print()

    if not npm_ok:
        print("   ⚠️  Frontend deps ยังไม่ได้ติดตั้ง — ก่อนรัน `npm run dev`:")
        print("      cd frontend && npm install")
        print()

    return True



# ───────────────────────────────────────────────────────────────
# Step 5b: Register to CT App Registry
# ───────────────────────────────────────────────────────────────


def _set_env_value(env_file: Path, key: str, value: str) -> None:
    """อัปเดต (หรือเพิ่ม) บรรทัด `key=value` ใน .env file"""
    if not env_file.exists():
        return
    lines = env_file.read_text(encoding="utf-8").splitlines()
    prefix = f"{key}="
    for i, line in enumerate(lines):
        if line.startswith(prefix):
            lines[i] = f"{key}={value}"
            break
    else:
        lines.append(f"{key}={value}")
    env_file.write_text("\n".join(lines) + "\n", encoding="utf-8")


def register_project(cfg: ProjectConfig, db_choice: dict, root: Path) -> None:
    """ส่ง registration ไป CT App Registry — เฟส 1 onboarding (ครั้งเดียวตอนตั้ง app).

    ดู docs/ops/registry.md §3:
    - endpoint `POST /api/v1/projects/register` เปิด — ไม่ต้องแนบ auth header
    - response 201 คืน `apiKey` ครั้งเดียว → เขียนกลับลง backend/.env ทันที
    - app จะอยู่สถานะ `pending` จนกว่า registry admin จะ approve
    ข้ามถ้า REGISTRY_URL ว่าง (registry ยังไม่ deploy — register ด้วยมือทีหลัง)
    """
    import urllib.error
    import urllib.request
    import json as json_mod

    # อ่าน REGISTRY_URL จาก backend/.env
    env_file = root / "backend" / ".env"
    registry_url = ""
    if env_file.exists():
        for line in env_file.read_text(encoding="utf-8").splitlines():
            if line.startswith("REGISTRY_URL="):
                registry_url = line.split("=", 1)[1].strip()

    if not registry_url:
        print("   ⏭️  ข้าม CT App Registry (REGISTRY_URL ว่าง)")
        print("      ตั้งค่าที่ backend/.env แล้ว register ด้วยมือ (ดู docs/ops/registry.md §3)")
        return

    # payload — camelCase ตาม docs/ops/registry.md §3.1
    # ไม่ส่ง backendUrl เพราะตอน setup ยังไม่รู้ production URL —
    # เพิ่มทีหลังผ่าน PATCH /projects/{slug} เพื่อเปิด health monitor (§4.1)
    payload = {
        "slug": cfg.project_slug,
        "displayName": cfg.project_display_name,
        "ownerEmail": cfg.owner,
        "businessUnit": cfg.bu,
        "authScope": cfg.auth_scope,
        "defaultLanguage": cfg.default_language,
        "techStack": {"backend": "FastAPI", "frontend": "React+TS", "db": "PostgreSQL"},
    }

    url = f"{registry_url.rstrip('/')}/api/v1/projects/register"
    data = json_mod.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        url, data=data,
        headers={"Content-Type": "application/json"},  # เปิด — ไม่แนบ X-API-Key
        method="POST",
    )

    try:
        with urllib.request.urlopen(req, timeout=10) as resp:
            body = json_mod.loads(resp.read().decode("utf-8"))
        api_key = body.get("apiKey", "")
        if api_key:
            _set_env_value(env_file, "REGISTRY_API_KEY", api_key)
            print("   ✅ ลงทะเบียนแล้ว — apiKey ถูกเขียนลง backend/.env (REGISTRY_API_KEY)")
        else:
            print("   ✅ ลงทะเบียนแล้ว — response ไม่มี apiKey, ตรวจสอบกับ admin")
        print("   ⏳ สถานะ: pending — ติดต่อ registry admin (ป่าน/IT) เพื่อ approve")
        print("      telemetry push จะได้ 403 จนกว่าจะ approve (เป็นเรื่องปกติ)")
    except urllib.error.HTTPError as e:
        if e.code == 409:
            print(f"   ℹ️  slug '{cfg.project_slug}' เคยลงทะเบียนแล้ว — ใช้ API key เดิม")
        else:
            print(f"   ⚠️  Registry ตอบ {e.code} — registration ไม่สำเร็จ")
            print("      ดู docs/ops/registry.md §6 แล้ว register ใหม่ด้วยมือ")
    except Exception as e:
        print(f"   ⚠️  ส่ง registration ไม่สำเร็จ: {e}")
        print("      register ใหม่ได้เมื่อ CT App Registry พร้อม (ดู docs/ops/registry.md §3)")


# ───────────────────────────────────────────────────────────────
# Step 5c: Spawn dev servers (optional, auto-start on confirm)
# ───────────────────────────────────────────────────────────────


def _spawn_dev_servers(root: Path, db_choice: dict | None) -> bool:
    """Open backend + frontend in their own terminal windows so the user
    sees logs side-by-side instead of having to copy/paste commands.

    Returns True if both windows were spawned, False if the platform isn't
    supported or spawning failed (caller falls back to printed instructions).

    Why two windows: uvicorn --reload and `npm run dev` are long-running
    foreground processes — they can't share a single terminal without
    losing log clarity. We hand each its own window and let the OS handle
    process management. setup.py exits as soon as both are launched.

    Windows: `start "Title" cmd /k <cmd>` — start is a cmd builtin so it
        needs shell=True. /k keeps the window open after the command exits
        (so a crash leaves logs visible).
    macOS:   osascript drives Terminal.app to open a new window and run
        the command. iTerm users get the system Terminal — close enough.
    Linux:   try common terminal emulators in order; bail if none found.
        Wayland users on a non-GNOME desktop may not have a default and
        will need to launch by hand — we print instructions then.
    """
    backend_dir = root / "backend"
    frontend_dir = root / "frontend"
    db_port = db_choice.get("port", 5432) if db_choice else 5432

    if sys.platform == "win32":
        try:
            # Backend window — set DB env vars locally then start uvicorn.
            # NO space before `&&`: in cmd.exe `set VAR=value<space>&&` stores
            # the value INCLUDING that trailing space (so DB_HOST becomes
            # "localhost "), and asyncpg then fails getaddrinfo on the spaced
            # host → every DB query (login) 500s while /health still works.
            # Putting `&&` flush against the value keeps it clean. (Dogfood
            # 2026-06-01: this was the real "Incorrect email or password" —
            # the login endpoint was crashing, not rejecting credentials.)
            backend_cmd = (
                f"set DB_HOST=localhost&& set DB_PORT={db_port}&& "
                "uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
            )
            subprocess.Popen(
                f'start "CT Backend" cmd /k "{backend_cmd}"',
                shell=True, cwd=backend_dir,
            )
            # Frontend window — npm run dev (vite).
            subprocess.Popen(
                'start "CT Frontend" cmd /k "npm run dev"',
                shell=True, cwd=frontend_dir,
            )
            return True
        except OSError as exc:
            print(f"   ⚠️  เปิด terminal ใหม่ไม่สำเร็จ: {exc}")
            return False

    if sys.platform == "darwin":
        # AppleScript escapes — paths with backslashes break the script,
        # but macOS paths don't have backslashes in practice.
        backend_script = (
            f'cd "{backend_dir}" && '
            f"export DB_HOST=localhost DB_PORT={db_port} && "
            "uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
        )
        frontend_script = f'cd "{frontend_dir}" && npm run dev'
        try:
            subprocess.Popen([
                "osascript", "-e",
                f'tell application "Terminal" to do script "{backend_script}"',
            ])
            subprocess.Popen([
                "osascript", "-e",
                f'tell application "Terminal" to do script "{frontend_script}"',
            ])
            return True
        except OSError as exc:
            print(f"   ⚠️  เปิด Terminal.app ไม่สำเร็จ: {exc}")
            return False

    # Linux — try common terminal emulators
    import shutil as _shutil  # local import — mirrors pattern elsewhere
    backend_sh = (
        f'cd "{backend_dir}" && '
        f"export DB_HOST=localhost DB_PORT={db_port} && "
        "uvicorn app.main:app --reload --host 0.0.0.0 --port 8000; "
        'echo "Press Enter to close"; read'
    )
    frontend_sh = (
        f'cd "{frontend_dir}" && npm run dev; '
        'echo "Press Enter to close"; read'
    )
    for term in ("gnome-terminal", "konsole", "xfce4-terminal",
                 "x-terminal-emulator", "xterm"):
        if _shutil.which(term):
            try:
                if term == "gnome-terminal":
                    subprocess.Popen([term, "--", "bash", "-c", backend_sh])
                    subprocess.Popen([term, "--", "bash", "-c", frontend_sh])
                elif term == "konsole":
                    subprocess.Popen([term, "-e", "bash", "-c", backend_sh])
                    subprocess.Popen([term, "-e", "bash", "-c", frontend_sh])
                else:
                    subprocess.Popen([term, "-e", f"bash -c '{backend_sh}'"])
                    subprocess.Popen([term, "-e", f"bash -c '{frontend_sh}'"])
                return True
            except OSError as exc:
                print(f"   ⚠️  เปิด {term} ไม่สำเร็จ: {exc}")
                return False

    print("   ⚠️  ไม่พบ terminal emulator ที่รองรับ — กรุณาเปิด terminal เอง")
    return False


# ───────────────────────────────────────────────────────────────
# Step 6: Summary
# ───────────────────────────────────────────────────────────────


def print_summary(cfg: ProjectConfig, servers_started: bool = False) -> None:
    print("=" * 60)
    print("  ✅ Setup เสร็จ!")
    print("=" * 60)
    print()
    print(f"  Project: {cfg.project_display_name}")
    print(f"  Auth:    {cfg.auth_scope}")
    print()

    if servers_started:
        print("  🚀 Dev servers ถูกเปิดใน terminal ใหม่ 2 อันแล้ว")
        print("     (Backend + Frontend) — ดู log ใน window ที่เพิ่งเด้งขึ้น")
        print()
    else:
        # Print manual instructions only when auto-start was skipped or failed.
        print("  ── เปิด Terminal ใหม่ 2 อัน ────────────────────────────")
        print()
        print("  Terminal 1 — Backend:")
        print("     cd backend")
        print("     set DB_HOST=localhost   (Windows)")
        if cfg.bootstrap_admin_email:
            print("     python -m app.seed                       (ครั้งแรกเท่านั้น)")
        print("     uvicorn app.main:app --reload --host 0.0.0.0 --port 8000")
        print()
        print("  Terminal 2 — Frontend:")
        print("     cd frontend")
        print("     npm run dev")
        print()
    print("  ── URLs ─────────────────────────────────────────────────")
    print()
    print("     Frontend:  http://localhost:5173")
    print("     API:       http://localhost:8000")
    print("     API Docs:  http://localhost:8000/docs")
    print()
    print("  ── Keys ที่ยังว่าง (เพิ่มใน backend/.env เมื่อพร้อม) ──")
    print()
    if cfg.auth_scope in ("both", "internal_only"):
        print("     AZURE_AD_TENANT_ID      → Azure Portal")
        print("     AZURE_AD_CLIENT_ID      → Azure Portal")
        print("     AZURE_AD_CLIENT_SECRET  → Azure Portal")
    print("     CLAUDE_API_KEY          → https://console.anthropic.com/")
    print()

    if cfg.bootstrap_admin_email:
        print("  ── Bootstrap super admin (เปิด /login ด้วย account นี้) ──")
        print()
        print(f"     Email:    {cfg.bootstrap_admin_email}")
        print(f"     Type:     {cfg.bootstrap_admin_auth_type}")
        if cfg.bootstrap_initial_password:
            print("     Password: เก็บไว้ใน backend/.env แล้ว (AUTH_BOOTSTRAP_INITIAL_PASSWORD)")
            print()
            print("     ⚠️  หลังรัน 'python -m app.seed' สำเร็จและ login ใช้งานได้:")
            print("         ลบบรรทัด AUTH_BOOTSTRAP_INITIAL_PASSWORD ใน backend/.env")
        else:
            print("     (Azure AD user — record สร้างตอน seed, role attach เมื่อ login ครั้งแรก)")
        print()

    print("  📖 AI agents: อ่าน CLAUDE.md → AGENTS.md ก่อนเริ่มงาน")
    print()


# ───────────────────────────────────────────────────────────────
# Target-dir resolution (Layout A vs sibling-zip)
# ───────────────────────────────────────────────────────────────
#
# Two supported layouts:
#
#   Layout A (default):
#       my-app/                      ← project root = template copy
#         AGENTS.md, scripts/setup.py, ...
#       User: copy template → cd my-app → run scripts/setup.py
#       Target dir = script_path.parent.parent (the template copy itself)
#
#   Sibling-zip (advanced):
#       parent/
#         web-app-standard/          ← unchanged template (read-only)
#           scripts/setup.py
#         my-app/                    ← empty / fresh project dir
#       User: cd my-app → run ../web-app-standard/scripts/setup.py
#                         --project-dir .
#       Target dir = the sibling project dir (cwd, or --project-dir)
#
# The bug: without --project-dir, sibling-zip layout makes
# `script_path.parent.parent` resolve to web-app-standard/ — the
# scaffolder would then write project.config, .env, backend/ etc. into
# the template repo itself, leaving my-app/ empty.


def _is_template_dir(path: Path) -> bool:
    """True if `path` is the canonical upstream web-app-standard repo.

    Heuristic: template-shaped files PLUS a .git/config whose remote URL
    looks like the CT-IT-Center upstream. Layout-A copies (made with
    `robocopy ... /XD .git`) have no .git and pass this check, even though
    they have setup.py/scaffold.py/AGENTS.md copied in.

    A user who clones a fork has a fork remote, not the canonical upstream
    → not detected → allowed. Only refused: someone running scripts/setup.py
    directly against an actual clone of CT-IT-Center/WEB-APP-STANDARD.
    """
    has_template_shape = (
        (path / "scripts" / "setup.py").exists()
        and (path / "scripts" / "scaffold.py").exists()
        and (path / "AGENTS.md").exists()
    )
    if not has_template_shape:
        return False
    git_config = path / ".git" / "config"
    if not git_config.exists():
        return False
    try:
        cfg = git_config.read_text(encoding="utf-8", errors="ignore").lower()
    except OSError:
        return False
    return "web-app-standard" in cfg


def _looks_like_fresh_project_dir(path: Path) -> bool:
    """True if `path` is empty or contains only innocuous files.

    Used to auto-detect sibling-zip layout: if cwd is empty-ish and not
    the template, we can safely scaffold into it without prompting.
    """
    if not path.is_dir():
        return False
    allowed = {".git", ".gitignore", "README.md", ".gitkeep", ".DS_Store"}
    for entry in path.iterdir():
        if entry.name in allowed:
            continue
        return False
    return True


def _resolve_project_dir(
    script_path: Path, cli_arg: str | None
) -> tuple[Path, str]:
    """Decide which directory to scaffold into.

    Returns (target_dir, layout_description). Raises SystemExit on
    unrecoverable ambiguity / template-dir conflict.
    """
    standard_root = script_path.parent.parent  # web-app-standard/ when sibling-zip; project root when Layout A
    cwd = Path.cwd().resolve()

    # Explicit override wins
    if cli_arg is not None:
        target = Path(cli_arg).resolve()
        if not target.exists():
            print(f"❌ --project-dir ไม่มีอยู่: {target}")
            sys.exit(1)
        if _is_template_dir(target):
            print("❌ --project-dir ชี้ไปที่ web-app-standard template เอง")
            print(f"   target: {target}")
            print()
            print("   เลือกหนึ่งใน:")
            print("   - Layout A: copy template → cd เข้า copy → run scripts/setup.py")
            print("   - Sibling-zip: cd ไป my-app ใหม่ → run ../web-app-standard/scripts/setup.py --project-dir .")
            sys.exit(1)
        return target, "explicit --project-dir"

    # No CLI arg: detect layout
    # Case 1: script lives inside the project (Layout A)
    #   standard_root has AGENTS.md AND we are running from inside it
    #   → scaffold into standard_root (the user's copy of the template)
    if (standard_root / "AGENTS.md").exists() and not _looks_like_fresh_project_dir(standard_root):
        # Sub-case: cwd is a sibling fresh dir AND template is read-only?
        # If cwd != standard_root AND cwd looks fresh AND cwd is NOT the
        # template, prefer cwd (sibling-zip layout).
        if (
            cwd != standard_root
            and not _is_template_dir(cwd)
            and _looks_like_fresh_project_dir(cwd)
        ):
            return cwd, "sibling-zip (cwd is fresh, auto-detected)"
        # Default: Layout A — scaffold into the template copy
        return standard_root, "Layout A (script_path.parent.parent)"

    # Case 2: script's parent.parent doesn't even look like a template
    #   → fall back to cwd
    if cwd != standard_root and not _is_template_dir(cwd):
        return cwd, "cwd fallback"

    print("❌ ไม่สามารถหา project dir ที่ปลอดภัย")
    print(f"   script: {script_path}")
    print(f"   cwd:    {cwd}")
    print()
    print("   ใช้ --project-dir <path> เพื่อระบุ project dir โดยตรง")
    sys.exit(1)


# ───────────────────────────────────────────────────────────────
# Main
# ───────────────────────────────────────────────────────────────


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="setup.py",
        description="Chia Tai Web App Standard — Project Setup",
    )
    parser.add_argument(
        "--project-dir",
        dest="project_dir",
        default=None,
        help=(
            "Path ที่จะ scaffold project ไป (default: auto-detect). "
            "ใช้สำหรับ sibling-zip layout: --project-dir . จาก my-app/ ใหม่"
        ),
    )
    parser.add_argument(
        "--database-mode",
        choices=("new", "existing"),
        default="new",
        help=(
            "Database ownership mode (default: new). "
            "Use 'existing' to configure a connection without creating or migrating schema."
        ),
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    _ensure_utf8_stdio()
    args = _parse_args(argv)

    script_path = Path(__file__).resolve()
    root = _resolve_project_dir(script_path, args.project_dir)[0]

    # Guard: refuse to scaffold INTO the web-app-standard template repo
    if _is_template_dir(root):
        print("❌ ปฏิเสธ — target dir เป็น web-app-standard template เอง")
        print(f"   target: {root}")
        print()
        print("   การ scaffold ไปยังที่นี่จะเขียนทับ template repo. เลือกหนึ่งใน:")
        print()
        print("   Layout A (default):")
        print("     1. copy web-app-standard ไป folder ใหม่ (เช่น my-app/)")
        print("     2. cd my-app")
        print("     3. python scripts/setup.py")
        print()
        print("   Sibling-zip (advanced):")
        print("     1. สร้าง folder ใหม่ ข้าง ๆ web-app-standard/ (เช่น my-app/)")
        print("     2. cd my-app")
        print("     3. python ../web-app-standard/scripts/setup.py --project-dir .")
        print()
        return 1

    if not (root / "AGENTS.md").exists():
        # In sibling-zip layout we expect AGENTS.md to be copied during
        # scaffold. But Layout A requires AGENTS.md to already exist.
        # If the dir is fresh, that's fine — but we still need a sentinel.
        # We treat missing AGENTS.md as "fresh project dir" → ok, the
        # scaffolder will populate it. Warn but continue.
        if not _looks_like_fresh_project_dir(root):
            print(f"⚠️  AGENTS.md ไม่พบที่ {root} และ folder ไม่ว่าง")
            print("   กรุณารันจาก root ของ project หรือใช้ --project-dir <fresh-dir>")
            return 1

    # ตรวจ environment
    env = check_environment()
    if not handle_env_issues(env, database_mode=args.database_mode):
        return 1

    # ถาม project config
    try:
        cfg = collect_config(root)
    except (KeyboardInterrupt, EOFError):
        print("\n\nยกเลิก")
        return 130

    # ถาม DB
    db_name = cfg.project_slug.replace("-", "_")
    if args.database_mode == "existing":
        db_choice = choose_existing_database(db_name)
    else:
        db_choice = choose_database(
            db_name,
            env=env,
            auth_required=bool(cfg.bootstrap_admin_email),
        )

    # Confirm
    print("─" * 60)
    print()
    print(f"   Project: {cfg.project_display_name} ({cfg.project_slug})")
    print(f"   Owner:   {cfg.owner}  |  BU: {cfg.bu}")
    print(f"   Auth:    {cfg.auth_scope}")
    if db_choice.get("skip"):
        print("   DB:      ข้าม")
    elif db_choice.get("existing_database"):
        print(
            "   DB:      existing "
            f"{db_choice['host']}:{db_choice['port']}/{db_choice['db_name']}"
        )
        print("            schema setup: skipped (safe default)")
    elif db_choice.get("use_existing"):
        if db_choice.get("native"):
            print(f"   DB:      native PostgreSQL (port {db_choice['port']}, superuser: {db_choice.get('pg_user', 'postgres')})")
        else:
            print(f"   DB:      ใช้ {db_choice['container_name']} (port {db_choice['port']})")
        print(f"            database='{db_choice.get('db_name', db_name)}'  user='{db_choice.get('db_user', db_name)}'")
    else:
        print(f"   DB:      Docker container ใหม่ (port {db_choice.get('port', 5432)})")
        print(f"            database='{db_choice.get('db_name', db_name)}'  user='{db_choice.get('db_user', db_name)}'")
    print()
    if not _confirm("   ดำเนินการ?", default_yes=True):
        print("ยกเลิก")
        return 0

    print()

    # Generate files
    generate_files(cfg, root, db_choice)

    # Install + Start
    success = install_and_start(root, db_choice)

    # Register to CT App Registry
    print("── CT App Registry ───────────────────────────────────────")
    print()
    register_project(cfg, db_choice, root)
    print()

    # Auto-start dev servers — opens 2 new terminal windows so the user
    # sees uvicorn + vite logs without having to copy/paste commands.
    # Skip if install_and_start failed (servers would just crash and the
    # window-spam adds noise to an already-broken setup).
    servers_started = False
    if (
        success
        and not db_choice.get("skip")
        and not db_choice.get("existing_database")
    ):
        print("── Start Dev Servers ─────────────────────────────────────")
        print()
        if _confirm("   เปิด Backend + Frontend ใน terminal ใหม่เลยไหม?",
                    default_yes=True):
            servers_started = _spawn_dev_servers(root, db_choice)
            if servers_started:
                print("   ✅ Servers ถูกเปิดใน terminal ใหม่ 2 อันแล้ว")
            else:
                print("   ⚠️  Auto-start ไม่สำเร็จ — รันตามวิธีด้านล่างเอง")
        print()

    # Summary
    print_summary(cfg, servers_started=servers_started)

    if not success:
        print("  ⚠️  บางขั้นตอนมีปัญหา — ดู error ด้านบน")
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
